config/routes.rb
Taskmanager::Application.routes.draw do

  scope module: :web do
    root to: 'stories#index'

    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create]

    resources :stories do
      put :next_state, on: :member
      scope module: :stories do
        resources :comments, only: [:create, :destroy]
      end
    end
  end


end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  belongs_to :assign_to_user, class_name: User
  has_many :comments, dependent: :destroy

  attr_accessible :assign_to_user_id, :description, :title, :user_id

  validates :title, presence: true
  validates :user, presence: true
  validates :assign_to_user, presence: true
  validates :description, presence: true

  state_machine :state, initial: :new do

    event :start do
      transition new: :started
    end

    event :finish do
      transition started: :finished
    end

    event :accept do
      transition finished: :accepted
    end

    event :reject do
      transition finished: :rejected
    end

    event :restart do
      transition rejected: :started
    end

  end
end

app/models/story/comment.rb
class Story::Comment < ActiveRecord::Base

  belongs_to :story
  belongs_to :user

  attr_accessible :text

  validates :user, presence: true
  validates :story, presence: true
  validates :text, presence: true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :destroy, :edit, :update, :next_state]
  before_filter(:only => [:destroy, :edit, :update]) { |s| require_owner Story.find(params[:id]).user }
  before_filter :require_owner_or_assigned_user, :only => :next_state

  def next_state
    notice = 'some errors'
    @story = Story.find(params[:id])
    state = params[:next_state]
    if @story && state.to_sym.in?(@story.state_events)
      @story.fire_state_event(state)
      notice = 'New state'
    end

    redirect_to @story, :notice => notice
  end

  def index
    @search = Story.search(params[:q])
    @stories = @search.result(:distinct => true)
  end

  def show
    @story = Story.find(params[:id])

  end

  def new
    @story = Story.new

  end

  def edit
    @story = Story.find(params[:id])
  end

  def create
    @story = Story.new(params[:story].merge(:user_id => current_user.id))

    if @story.save then
      redirect_to @story, notice: 'Story was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @story = Story.find(params[:id])

    if @story.update_attributes(params[:story])
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    redirect_to stories_url

  end

  private
  def require_owner_or_assigned_user
    unless current_user.in? [Story.find(params[:id]).user, User.find(Story.find(params[:id]).assign_to_user_id)]
      redirect_to root_path, :notice => 'only for owner or assigned user'
    end
  end

end

app/controllers/web/stories/application_controller.rb
class Web::Stories::ApplicationController < Web::ProtectedApplicationController

  helper_method :current_story

  def current_story
    @current_story = Story.find params[:story_id]
  end

end

app/controllers/web/stories/comments_controller.rb
class Web::Stories::CommentsController < Web::Stories::ApplicationController

  def create

    @comment = current_story.comments.build(params[:story_comment])
    @comment.user = current_user

    if @comment.save
      flash_success
      redirect_to @comment.story
    else
      flash_error
      redirect_to request.referer
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy

    redirect_to story_path(@comment.story)

  end

end

app/controllers/web/stories/story_comments_controller.rb
class Web::Stories::StoryCommentsController < Web::ApplicationController
  before_filter :require_login

  #FIXME как это можно улучшить?
  before_filter(only: [:destroy]) { |sc| sc.require_owner StoryComment.find(params[:id]).user}

  def create
    new_comment_params = params[:story_comment]
    new_comment_params[:user_id] = current_user.id
    new_comment_params[:story_id] = params[:story_id]

    @story_comment = StoryComment.new(new_comment_params)

      if @story_comment.save
        redirect_to @story_comment.story, notice: 'Story comment was successfully created.'
      else
        redirect_to request.referer
      end
  end

  def destroy
    @story_comment = StoryComment.find(params[:id])
    @story_comment.destroy

    redirect_to story_path(@story_comment.story)

  end

end

app/controllers/web/stories_controller.rb
class Web::StoriesController < Web::ProtectedApplicationController
  skip_before_filter :authenticate_user!, :only => [:index, :show]

  def next_state

    return unless owner_or_assigned_user?

    @story = Story.find(params[:id])
    @story.fire_state_event(params[:event])
    flash_success

    redirect_to @story
  end

  def index
    @search = Story.search(params[:q])
    @stories = @search.result(distinct: true)
  end

  def show
    @story = Story.find(params[:id])

  end

  def new
    @story = Story.new

  end

  def edit
    @story = current_user.stories.find(params[:id])
  end

  def create
    @story =  current_user.stories.build params[:story]

    if @story.save
      flash_success
      redirect_to @story
    else
      flash_error
      render action: 'new'
    end
  end

  def update
    @story = current_user.stories.find(params[:id])
    if @story.update_attributes(params[:story])
      flash_success
      redirect_to @story
    else
      flash_error
      render action: 'edit'
    end
  end

  def destroy
    @story = current_user.stories.find(params[:id])
    @story.destroy

    flash_success
    redirect_to stories_url

  end

  private
  def owner_or_assigned_user?
    story = Story.find(params[:id])
    current_user.in? [story.user, story.assign_to_user]
  end

end

app/helpers/web/stories_helper.rb
module Web::StoriesHelper
end

app/views/web/stories/_form.html.haml
= simple_form_for @story do |f|
  = f.input :title
  = f.input :description, as: :text, input_html: { cols: 30,  rows: 5 }
  = f.association :assign_to_user, label_method: :email, prompt: t('story.select_user')
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to t('cancel'), stories_path, class: 'btn'

app/views/web/stories/edit.html.haml
.page-header
  %h1=t '.title'
= render partial: 'form'

app/views/web/stories/index.html.haml
.page-header
  %h1=t '.title'
.row
  = simple_form_for @search, url: root_path, html: { class: 'form-inline'} do |f|
    .span4
      =f.input :user_id_eq, collection: User.all, label_method: :email, required: false, input_html: {class: 'inline'}
    .span4
      =f.input :state_eq, collection: Story.state_machine.states.map(&:name), required: false, input_html: {class: 'inline'}
    .span4
      =f.button :submit, 'find', class: 'btn btn-primary', input_html: {class: 'inline'}
%br
.row
  .span12
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th= Story.human_attribute_name(:id)
          %th= Story.human_attribute_name(:owner_email)
          %th= Story.human_attribute_name(:title)
          %th= Story.human_attribute_name(:description)
          %th= Story.human_attribute_name(:state)
          %th= Story.human_attribute_name(:assign_to_user_email)
          %th= Story.human_attribute_name(:created_at)
          %th=t '.actions', default: t('helpers.actions')
      %tbody
        - @stories.each do |story|
          %tr
            %td=  story.id
            %td= story.user.email
            %td= link_to story.title, story_path(story)
            %td= story.description
            %td= story.state
            %td= story.assign_to_user.email
            %td=l story.created_at
            %td
              -if owner? story.user
                = link_to t('.edit', default: t('helpers.links.edit')), edit_story_path(story), class: 'btn btn-mini'
                = link_to t('.destroy', default: t('helpers.links.destroy')), story_path(story), method: :delete, data: { confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger'
    -if signed_in?
      = link_to t('.new', default: t('helpers.links.new')), new_story_path, class: 'btn btn-primary'

app/views/web/stories/new.html.haml
.page-header
  %h1=t '.title'
= render partial: 'form'

app/views/web/stories/show.html.haml
.row
  .span6
    .page-header
      %h1=t '.title'
    %p
      %strong= Story.human_attribute_name(:user_id) + ':'
      %br
      = @story.user.email
    %p
      %strong= Story.human_attribute_name(:title) + ':'
      %br
      = @story.title
    %p
      %strong= Story.human_attribute_name(:description) + ':'
      %br
      = @story.description
    %p
      %strong= Story.human_attribute_name(:state) + ':'
      %br
      = @story.state
      %br
      change to (only for owner and assigned user):
      %br
      - if owner?(@story.user) || owner?(@story.assign_to_user)
        - @story.state_events.each do |e|
          = link_to e, next_state_story_path(@story, event: e), method: :put, class: 'btn btn-mini'
    %p
      %strong= Story.human_attribute_name(:assign_to_user) + ':'
      %br
      = @story.assign_to_user.email
    .form-actions
      = link_to t('.back', default: t('helpers.links.back')), stories_path, class: 'btn'
      - if owner? @story.user
        = link_to t('.edit', default: t('helpers.links.edit')), edit_story_path(@story), class: 'btn'
        = link_to t('.destroy', default: t('helpers.links.destroy')), story_path(@story), method: 'delete', data: { confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?')) }, class: 'btn btn-danger'
  .span6
    .page-header
      %h1 Comments

    - @story.comments.each do |story_comment|
      %p
        = "#{story_comment.user.email} : #{story_comment.text}"
        - if owner? story_comment.user
          =link_to content_tag(:button, raw('&times;'), class: 'close'), story_comment_path(@story,story_comment), method: :delete, confirm: t('story_comment.delete_question')
    - if signed_in?
      .form-actions
        = simple_form_for @story.comments.build, url: story_comments_path(@story) do |f|
          = f.input :text, as: :text, input_html: { cols: 50,  rows: 3 }
          = f.button :submit, 'add comment', class: 'btn btn-primary'