config/routes.rb
Taskmanager::Application.routes.draw do

  scope module: :web do
    root to: 'stories#index'

    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create]

    resources :stories do
      put :next_state, on: :member
      scope module: :stories do
        resources :comments, only: [:create, :destroy]
      end
    end
  end


end

app/views/layouts/_navigation.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand(href="/") TM
      .container.nav-collapse
        %ul.nav(class="pull-right")
          - if signed_in?
            %li= link_to t('sign_out') +' '+ current_user.email, session_path(current_user), method: :delete
          - else
            %li= link_to t('registration'), new_user_path
            %li= link_to t('sign_in'), new_session_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'Taskmanager'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js'
    = stylesheet_link_tag 'application', media: 'all'
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    = render partial: 'layouts/navigation'

    .container

      .row
        .span12
          = bootstrap_flash
          = yield

      %footer
        -#%p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag 'application'